PORTNAME=	ngstep-systempreferences
DISTVERSION=	20250531
CATEGORIES=	deskutils gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	System Preferences application for NgSTEP
WWW=		https://github.com/ngstep/

LICENSE=	GPLv2

USE_GITHUB=	yes
GH_ACCOUNT=	ngstep
GH_TAGNAME=	758c95c

USES=		ngstep
USE_NGSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_SYSTEM_LIBRARIES}

.include <bsd.port.mk>